// Branding values come from branding.json, which is generated by:
//   bun scripts/write-branding.ts
// That script reads from apps/chat/branding.ts — the single source of truth.
const { APP_NAME, APP_PREFIX, ORG_NAME } = require("./branding.json");

/** @type {import('electron-builder').Configuration} */
module.exports = {
  appId: `dev.${APP_PREFIX}.app`,
  productName: APP_NAME,
  copyright: `Copyright © ${new Date().getFullYear()} ${ORG_NAME}`,

  directories: {
    output: "release",
  },

  files: ["dist/**", "build/**", "entitlements.mac.plist", "package.json"],

  publish: {
    provider: "github",
    owner: "FranciscoMoretti",
    repo: "chat-js",
    releaseType: "release",
  },

  mac: {
    target: [{ target: "dmg", arch: ["x64", "arm64"] }],
    category: "public.app-category.productivity",
    hardenedRuntime: true,
    entitlements: "entitlements.mac.plist",
    entitlementsInherit: "entitlements.mac.plist",
    gatekeeperAssess: false,
    protocols: [{ name: `${APP_NAME} Auth`, schemes: [APP_PREFIX] }],
  },

  dmg: {
    sign: false,
  },

  win: {
    target: [{ target: "nsis", arch: ["x64"] }],
    protocols: [{ name: `${APP_NAME} Auth`, schemes: [APP_PREFIX] }],
  },

  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: "always",
    createStartMenuShortcut: true,
  },

  linux: {
    target: [{ target: "AppImage", arch: ["x64"] }],
    category: "Network",
  },
};
